2015-11-06 23:59:03 Error: [Cake\Routing\Exception\MissingControllerException] Controller class Articles could not be found.
Exception Attributes: array (
  'class' => 'Articles',
  'plugin' => NULL,
  'prefix' => NULL,
  '_ext' => NULL,
)
Request URL: /cakephp-3-1-1/
Stack Trace:
#0 C:\xampp\htdocs\cakephp-3-1-1\webroot\index.php(37): Cake\Routing\Dispatcher->dispatch(Object(Cake\Network\Request), Object(Cake\Network\Response))
#1 {main}


2015-11-07 01:48:34 Error: Fatal Error (4): syntax error, unexpected 'public' (T_PUBLIC) in [C:\xampp\htdocs\cakephp-3-1-1\src\Controller\UsersController.php, line 4]
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 191
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 90
[main] - [internal], line ??



2015-11-07 01:48:35 Error: [Cake\Error\FatalErrorException] syntax error, unexpected 'public' (T_PUBLIC)
Request URL: /cakephp-3-1-1/users/login
Stack Trace:
#0 C:\xampp\htdocs\cakephp-3-1-1\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(90): Cake\Error\BaseErrorHandler->handleFatalError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 4)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2015-11-07 01:50:59 Error: Fatal Error (4): syntax error, unexpected '<' in [C:\xampp\htdocs\cakephp-3-1-1\src\Controller\UsersController.php, line 3]
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 191
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 90
[main] - [internal], line ??



2015-11-07 01:51:00 Error: [Cake\Error\FatalErrorException] syntax error, unexpected '<'
Request URL: /cakephp-3-1-1/users/login
Stack Trace:
#0 C:\xampp\htdocs\cakephp-3-1-1\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(90): Cake\Error\BaseErrorHandler->handleFatalError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 3)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2015-11-07 01:55:13 Error: [Cake\Routing\Exception\MissingControllerException] Controller class Logout could not be found.
Exception Attributes: array (
  'class' => 'Logout',
  'plugin' => NULL,
  'prefix' => NULL,
  '_ext' => NULL,
)
Request URL: /cakephp-3-1-1/logout
Stack Trace:
#0 C:\xampp\htdocs\cakephp-3-1-1\webroot\index.php(37): Cake\Routing\Dispatcher->dispatch(Object(Cake\Network\Request), Object(Cake\Network\Response))
#1 {main}


2015-11-07 01:55:42 Error: [Cake\Routing\Exception\MissingControllerException] Controller class Add could not be found.
Exception Attributes: array (
  'class' => 'Add',
  'plugin' => NULL,
  'prefix' => NULL,
  '_ext' => NULL,
)
Request URL: /cakephp-3-1-1/add
Stack Trace:
#0 C:\xampp\htdocs\cakephp-3-1-1\webroot\index.php(37): Cake\Routing\Dispatcher->dispatch(Object(Cake\Network\Request), Object(Cake\Network\Response))
#1 {main}


2015-11-07 01:56:08 Error: [Cake\View\Exception\MissingTemplateException] Template file "Users\index.ctp" is missing.
Exception Attributes: array (
  'file' => 'Users\\index.ctp',
)
Request URL: /cakephp-3-1-1/users/
Stack Trace:
#0 C:\xampp\htdocs\cakephp-3-1-1\vendor\cakephp\cakephp\src\View\View.php(575): Cake\View\View->_getViewFileName(NULL)
#1 C:\xampp\htdocs\cakephp-3-1-1\vendor\cakephp\cakephp\src\Controller\Controller.php(611): Cake\View\View->render(NULL, NULL)
#2 C:\xampp\htdocs\cakephp-3-1-1\vendor\cakephp\cakephp\src\Routing\Dispatcher.php(120): Cake\Controller\Controller->render()
#3 C:\xampp\htdocs\cakephp-3-1-1\vendor\cakephp\cakephp\src\Routing\Dispatcher.php(87): Cake\Routing\Dispatcher->_invoke(Object(App\Controller\UsersController))
#4 C:\xampp\htdocs\cakephp-3-1-1\webroot\index.php(37): Cake\Routing\Dispatcher->dispatch(Object(Cake\Network\Request), Object(Cake\Network\Response))
#5 {main}


2015-11-08 20:27:16 Error: [PDOException] SQLSTATE[HY000] [2002] No connection could be made because the target machine actively refused it.

Request URL: /cakephp-3-1-1/
Stack Trace:
#0 C:\xampp\htdocs\cakephp-3-1-1\vendor\cakephp\cakephp\src\Database\Driver\PDODriverTrait.php(48): PDO->__construct('mysql:host=loca...', 'root', '', Array)
#1 C:\xampp\htdocs\cakephp-3-1-1\vendor\cakephp\cakephp\src\Database\Driver\Mysql.php(90): Cake\Database\Driver\Mysql->_connect('mysql:host=loca...', Array)
#2 C:\xampp\htdocs\cakephp-3-1-1\vendor\cakephp\cakephp\src\Database\Schema\BaseSchema.php(45): Cake\Database\Driver\Mysql->connect()
#3 C:\xampp\htdocs\cakephp-3-1-1\vendor\cakephp\cakephp\src\Database\Dialect\MysqlDialectTrait.php(63): Cake\Database\Schema\BaseSchema->__construct(Object(Cake\Database\Driver\Mysql))
#4 C:\xampp\htdocs\cakephp-3-1-1\vendor\cakephp\cakephp\src\Database\Schema\Collection.php(52): Cake\Database\Driver\Mysql->schemaDialect()
#5 C:\xampp\htdocs\cakephp-3-1-1\vendor\cakephp\cakephp\src\Database\Schema\CachedCollection.php(43): Cake\Database\Schema\Collection->__construct(Object(Cake\Database\Connection))
#6 C:\xampp\htdocs\cakephp-3-1-1\vendor\cakephp\cakephp\src\Database\Connection.php(315): Cake\Database\Schema\CachedCollection->__construct(Object(Cake\Database\Connection), true)
#7 C:\xampp\htdocs\cakephp-3-1-1\vendor\cakephp\cakephp\src\ORM\Table.php(422): Cake\Database\Connection->schemaCollection()
#8 C:\xampp\htdocs\cakephp-3-1-1\vendor\cakephp\cakephp\src\ORM\Query.php(164): Cake\ORM\Table->schema()
#9 C:\xampp\htdocs\cakephp-3-1-1\vendor\cakephp\cakephp\src\ORM\Query.php(122): Cake\ORM\Query->addDefaultTypes(Object(App\Model\Table\ArticlesTable))
#10 C:\xampp\htdocs\cakephp-3-1-1\vendor\cakephp\cakephp\src\ORM\Table.php(1228): Cake\ORM\Query->__construct(Object(Cake\Database\Connection), Object(App\Model\Table\ArticlesTable))
#11 C:\xampp\htdocs\cakephp-3-1-1\vendor\cakephp\cakephp\src\ORM\Table.php(931): Cake\ORM\Table->query()
#12 C:\xampp\htdocs\cakephp-3-1-1\src\Controller\ArticlesController.php(20): Cake\ORM\Table->find('all')
#13 [internal function]: App\Controller\ArticlesController->index()
#14 C:\xampp\htdocs\cakephp-3-1-1\vendor\cakephp\cakephp\src\Controller\Controller.php(429): call_user_func_array(Array, Array)
#15 C:\xampp\htdocs\cakephp-3-1-1\vendor\cakephp\cakephp\src\Routing\Dispatcher.php(114): Cake\Controller\Controller->invokeAction()
#16 C:\xampp\htdocs\cakephp-3-1-1\vendor\cakephp\cakephp\src\Routing\Dispatcher.php(87): Cake\Routing\Dispatcher->_invoke(Object(App\Controller\ArticlesController))
#17 C:\xampp\htdocs\cakephp-3-1-1\webroot\index.php(37): Cake\Routing\Dispatcher->dispatch(Object(Cake\Network\Request), Object(Cake\Network\Response))
#18 {main}


2015-11-08 20:27:38 Error: [Cake\Routing\Exception\MissingControllerException] Controller class Pizza could not be found.
Exception Attributes: array (
  'class' => 'Pizza',
  'plugin' => NULL,
  'prefix' => NULL,
  '_ext' => NULL,
)
Request URL: /cakephp-3-1-1/pizza/
Stack Trace:
#0 C:\xampp\htdocs\cakephp-3-1-1\webroot\index.php(37): Cake\Routing\Dispatcher->dispatch(Object(Cake\Network\Request), Object(Cake\Network\Response))
#1 {main}


2015-11-08 20:33:22 Error: Fatal Error (1): Call to a member function find() on boolean in [C:\xampp\htdocs\cakephp-3-1-1\src\Controller\PizzaController.php, line 20]
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 191
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 90
[main] - [internal], line ??



2015-11-08 20:33:22 Error: [Cake\Error\FatalErrorException] Call to a member function find() on boolean
Request URL: /cakephp-3-1-1/pizza/
Stack Trace:
#0 C:\xampp\htdocs\cakephp-3-1-1\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(90): Cake\Error\BaseErrorHandler->handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 20)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2015-11-08 20:33:28 Error: Fatal Error (1): Call to a member function find() on boolean in [C:\xampp\htdocs\cakephp-3-1-1\src\Controller\PizzaController.php, line 20]
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 191
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 90
[main] - [internal], line ??



2015-11-08 20:33:28 Error: [Cake\Error\FatalErrorException] Call to a member function find() on boolean
Request URL: /cakephp-3-1-1/Pizza/
Stack Trace:
#0 C:\xampp\htdocs\cakephp-3-1-1\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(90): Cake\Error\BaseErrorHandler->handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 20)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2015-11-08 20:42:57 Error: Fatal Error (1): Call to a member function newEntity() on boolean in [C:\xampp\htdocs\cakephp-3-1-1\src\Controller\PizzaController.php, line 44]
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 191
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 90
[main] - [internal], line ??



2015-11-08 20:42:58 Error: [Cake\Error\FatalErrorException] Call to a member function newEntity() on boolean
Request URL: /cakephp-3-1-1/Pizza/add/
Stack Trace:
#0 C:\xampp\htdocs\cakephp-3-1-1\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(90): Cake\Error\BaseErrorHandler->handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 44)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2015-11-08 20:43:29 Error: Fatal Error (1): Call to a member function newEntity() on boolean in [C:\xampp\htdocs\cakephp-3-1-1\src\Controller\PersonaldetailsController.php, line 26]
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 191
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 90
[main] - [internal], line ??



2015-11-08 20:43:29 Error: [Cake\Error\FatalErrorException] Call to a member function newEntity() on boolean
Request URL: /cakephp-3-1-1/PersonalDetails/add/
Stack Trace:
#0 C:\xampp\htdocs\cakephp-3-1-1\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(90): Cake\Error\BaseErrorHandler->handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 26)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2015-11-08 20:45:02 Error: Fatal Error (1): Call to a member function newEntity() on boolean in [C:\xampp\htdocs\cakephp-3-1-1\src\Controller\PersonaldetailsController.php, line 26]
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 191
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 90
[main] - [internal], line ??



2015-11-08 20:45:03 Error: [Cake\Error\FatalErrorException] Call to a member function newEntity() on boolean
Request URL: /cakephp-3-1-1/PersonalDetails/add/
Stack Trace:
#0 C:\xampp\htdocs\cakephp-3-1-1\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(90): Cake\Error\BaseErrorHandler->handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 26)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2015-11-08 20:45:39 Error: Fatal Error (1): Call to a member function find() on boolean in [C:\xampp\htdocs\cakephp-3-1-1\src\Controller\PersonaldetailsController.php, line 20]
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 191
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 90
[main] - [internal], line ??



2015-11-08 20:45:39 Error: [Cake\Error\FatalErrorException] Call to a member function find() on boolean
Request URL: /cakephp-3-1-1/PersonalDetails/
Stack Trace:
#0 C:\xampp\htdocs\cakephp-3-1-1\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(90): Cake\Error\BaseErrorHandler->handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 20)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2015-11-09 00:02:41 Error: [Cake\Routing\Exception\MissingControllerException] Controller class Pizza could not be found.
Exception Attributes: array (
  'class' => 'Pizza',
  'plugin' => NULL,
  'prefix' => NULL,
  '_ext' => NULL,
)
Request URL: /cakephp-3-1-1/Pizza/
Stack Trace:
#0 C:\xampp\htdocs\cakephp-3-1-1\webroot\index.php(37): Cake\Routing\Dispatcher->dispatch(Object(Cake\Network\Request), Object(Cake\Network\Response))
#1 {main}


2015-11-09 00:46:56 Warning: Warning (2): Creating default object from empty value in [C:\xampp\htdocs\cakephp-3-1-1\src\Controller\PersonaldetailsController.php, line 16]
Trace:
Cake\Error\BaseErrorHandler::handleError() - CORE\src\Error\BaseErrorHandler.php, line 138
App\Controller\PersonaldetailsController::index() - APP/Controller\PersonaldetailsController.php, line 16
Cake\Controller\Controller::invokeAction() - CORE\src\Controller\Controller.php, line 429
Cake\Routing\Dispatcher::_invoke() - CORE\src\Routing\Dispatcher.php, line 114
Cake\Routing\Dispatcher::dispatch() - CORE\src\Routing\Dispatcher.php, line 87
[main] - ROOT\webroot\index.php, line 37



2015-11-09 00:46:56 Error: Fatal Error (4): syntax error, unexpected '->' (T_OBJECT_OPERATOR) in [C:\xampp\htdocs\cakephp-3-1-1\src\Model\Table\PersonaldetailsTable.php, line 23]
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 191
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 90
[main] - [internal], line ??



2015-11-09 00:46:57 Error: [Cake\Error\FatalErrorException] syntax error, unexpected '->' (T_OBJECT_OPERATOR)
Request URL: /cakephp-3-1-1/PersonalDetails/
Stack Trace:
#0 C:\xampp\htdocs\cakephp-3-1-1\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(90): Cake\Error\BaseErrorHandler->handleFatalError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 23)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2015-11-09 01:11:01 Error: Fatal Error (4): syntax error, unexpected '->' (T_OBJECT_OPERATOR) in [C:\xampp\htdocs\cakephp-3-1-1\src\Model\Table\PersonaldetailsTable.php, line 23]
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 191
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 90
[main] - [internal], line ??



2015-11-09 01:11:01 Error: [Cake\Error\FatalErrorException] syntax error, unexpected '->' (T_OBJECT_OPERATOR)
Request URL: /cakephp-3-1-1/PersonalDetails/
Stack Trace:
#0 C:\xampp\htdocs\cakephp-3-1-1\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(90): Cake\Error\BaseErrorHandler->handleFatalError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 23)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2015-11-09 01:13:40 Error: [Cake\View\Exception\MissingTemplateException] Template file "PersonalDetails\index.ctp" is missing.
Exception Attributes: array (
  'file' => 'PersonalDetails\\index.ctp',
)
Request URL: /cakephp-3-1-1/PersonalDetails/
Stack Trace:
#0 C:\xampp\htdocs\cakephp-3-1-1\vendor\cakephp\cakephp\src\View\View.php(575): Cake\View\View->_getViewFileName(NULL)
#1 C:\xampp\htdocs\cakephp-3-1-1\vendor\cakephp\cakephp\src\Controller\Controller.php(611): Cake\View\View->render(NULL, NULL)
#2 C:\xampp\htdocs\cakephp-3-1-1\vendor\cakephp\cakephp\src\Routing\Dispatcher.php(120): Cake\Controller\Controller->render()
#3 C:\xampp\htdocs\cakephp-3-1-1\vendor\cakephp\cakephp\src\Routing\Dispatcher.php(87): Cake\Routing\Dispatcher->_invoke(Object(App\Controller\PersonaldetailsController))
#4 C:\xampp\htdocs\cakephp-3-1-1\webroot\index.php(37): Cake\Routing\Dispatcher->dispatch(Object(Cake\Network\Request), Object(Cake\Network\Response))
#5 {main}


2015-11-09 02:01:09 Error: [Cake\View\Exception\MissingTemplateException] Template file "PersonalDetails\add.ctp" is missing.
Exception Attributes: array (
  'file' => 'PersonalDetails\\add.ctp',
)
Request URL: /cakephp-3-1-1/personal-details/add
Stack Trace:
#0 C:\xampp\htdocs\cakephp-3-1-1\vendor\cakephp\cakephp\src\View\View.php(575): Cake\View\View->_getViewFileName(NULL)
#1 C:\xampp\htdocs\cakephp-3-1-1\vendor\cakephp\cakephp\src\Controller\Controller.php(611): Cake\View\View->render(NULL, NULL)
#2 C:\xampp\htdocs\cakephp-3-1-1\vendor\cakephp\cakephp\src\Routing\Dispatcher.php(120): Cake\Controller\Controller->render()
#3 C:\xampp\htdocs\cakephp-3-1-1\vendor\cakephp\cakephp\src\Routing\Dispatcher.php(87): Cake\Routing\Dispatcher->_invoke(Object(App\Controller\PersonaldetailsController))
#4 C:\xampp\htdocs\cakephp-3-1-1\webroot\index.php(37): Cake\Routing\Dispatcher->dispatch(Object(Cake\Network\Request), Object(Cake\Network\Response))
#5 {main}


2015-11-09 02:09:14 Error: Fatal Error (1): Call to a member function create() on boolean in [C:\xampp\htdocs\cakephp-3-1-1\src\Controller\PersonaldetailsController.php, line 49]
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 191
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 90
[main] - [internal], line ??



2015-11-09 02:09:14 Error: [Cake\Error\FatalErrorException] Call to a member function create() on boolean
Request URL: /cakephp-3-1-1/personal-details/add
Stack Trace:
#0 C:\xampp\htdocs\cakephp-3-1-1\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(90): Cake\Error\BaseErrorHandler->handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 49)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2015-11-09 02:11:00 Error: Fatal Error (1): Call to a member function create() on boolean in [C:\xampp\htdocs\cakephp-3-1-1\src\Controller\PersonaldetailsController.php, line 49]
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 191
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 90
[main] - [internal], line ??



2015-11-09 02:11:01 Error: [Cake\Error\FatalErrorException] Call to a member function create() on boolean
Request URL: /cakephp-3-1-1/personal-details/add
Stack Trace:
#0 C:\xampp\htdocs\cakephp-3-1-1\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(90): Cake\Error\BaseErrorHandler->handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 49)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2015-11-09 02:16:22 Error: Fatal Error (1): Call to a member function newEntity() on boolean in [C:\xampp\htdocs\cakephp-3-1-1\src\Controller\PersonaldetailsController.php, line 48]
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 191
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 90
[main] - [internal], line ??



2015-11-09 02:16:23 Error: [Cake\Error\FatalErrorException] Call to a member function newEntity() on boolean
Request URL: /cakephp-3-1-1/personal-details/add
Stack Trace:
#0 C:\xampp\htdocs\cakephp-3-1-1\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(90): Cake\Error\BaseErrorHandler->handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 48)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2015-11-09 02:19:49 Error: Fatal Error (1): Call to a member function newEntity() on boolean in [C:\xampp\htdocs\cakephp-3-1-1\src\Controller\PersonaldetailsController.php, line 48]
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 191
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 90
[main] - [internal], line ??



2015-11-09 02:19:50 Error: [Cake\Error\FatalErrorException] Call to a member function newEntity() on boolean
Request URL: /cakephp-3-1-1/personal-details/add
Stack Trace:
#0 C:\xampp\htdocs\cakephp-3-1-1\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(90): Cake\Error\BaseErrorHandler->handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 48)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2015-11-09 02:19:55 Error: Fatal Error (1): Call to a member function find() on boolean in [C:\xampp\htdocs\cakephp-3-1-1\src\Controller\PersonaldetailsController.php, line 24]
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 191
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 90
[main] - [internal], line ??



2015-11-09 02:19:55 Error: [Cake\Error\FatalErrorException] Call to a member function find() on boolean
Request URL: /cakephp-3-1-1/PersonalDetails/
Stack Trace:
#0 C:\xampp\htdocs\cakephp-3-1-1\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(90): Cake\Error\BaseErrorHandler->handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 24)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2015-11-09 02:22:25 Error: Fatal Error (1): Call to a member function newEntity() on boolean in [C:\xampp\htdocs\cakephp-3-1-1\src\Controller\PersonaldetailsController.php, line 48]
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 191
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 90
[main] - [internal], line ??



2015-11-09 02:22:25 Error: [Cake\Error\FatalErrorException] Call to a member function newEntity() on boolean
Request URL: /cakephp-3-1-1/personal-details/add
Stack Trace:
#0 C:\xampp\htdocs\cakephp-3-1-1\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(90): Cake\Error\BaseErrorHandler->handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 48)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2015-11-09 02:27:49 Error: Fatal Error (1): Call to a member function newEntity() on boolean in [C:\xampp\htdocs\cakephp-3-1-1\src\Controller\PersonaldetailsController.php, line 49]
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 191
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 90
[main] - [internal], line ??



2015-11-09 02:27:49 Error: [Cake\Error\FatalErrorException] Call to a member function newEntity() on boolean
Request URL: /cakephp-3-1-1/personal-details/add
Stack Trace:
#0 C:\xampp\htdocs\cakephp-3-1-1\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(90): Cake\Error\BaseErrorHandler->handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 49)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2015-11-09 02:27:55 Error: Fatal Error (1): Call to a member function newEntity() on boolean in [C:\xampp\htdocs\cakephp-3-1-1\src\Controller\PersonaldetailsController.php, line 49]
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 191
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 90
[main] - [internal], line ??



2015-11-09 02:27:55 Error: [Cake\Error\FatalErrorException] Call to a member function newEntity() on boolean
Request URL: /cakephp-3-1-1/personal-details/add
Stack Trace:
#0 C:\xampp\htdocs\cakephp-3-1-1\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(90): Cake\Error\BaseErrorHandler->handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 49)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2015-11-09 02:28:40 Error: Fatal Error (1): Call to a member function newEntity() on boolean in [C:\xampp\htdocs\cakephp-3-1-1\src\Controller\PersonaldetailsController.php, line 48]
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 191
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 90
[main] - [internal], line ??



2015-11-09 02:28:41 Error: [Cake\Error\FatalErrorException] Call to a member function newEntity() on boolean
Request URL: /cakephp-3-1-1/personal-details/add
Stack Trace:
#0 C:\xampp\htdocs\cakephp-3-1-1\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(90): Cake\Error\BaseErrorHandler->handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 48)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2015-11-09 02:28:45 Error: Fatal Error (1): Call to a member function newEntity() on boolean in [C:\xampp\htdocs\cakephp-3-1-1\src\Controller\PersonaldetailsController.php, line 48]
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 191
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 90
[main] - [internal], line ??



2015-11-09 02:28:46 Error: [Cake\Error\FatalErrorException] Call to a member function newEntity() on boolean
Request URL: /cakephp-3-1-1/personal-details/add
Stack Trace:
#0 C:\xampp\htdocs\cakephp-3-1-1\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(90): Cake\Error\BaseErrorHandler->handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 48)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2015-11-09 02:31:19 Error: Fatal Error (1): Call to a member function newEntity() on boolean in [C:\xampp\htdocs\cakephp-3-1-1\src\Controller\PersonaldetailsController.php, line 48]
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 191
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 90
[main] - [internal], line ??



2015-11-09 02:31:20 Error: [Cake\Error\FatalErrorException] Call to a member function newEntity() on boolean
Request URL: /cakephp-3-1-1/personal-details/add
Stack Trace:
#0 C:\xampp\htdocs\cakephp-3-1-1\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(90): Cake\Error\BaseErrorHandler->handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 48)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2015-11-09 02:31:26 Error: Fatal Error (1): Call to a member function newEntity() on boolean in [C:\xampp\htdocs\cakephp-3-1-1\src\Controller\PersonaldetailsController.php, line 48]
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 191
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 90
[main] - [internal], line ??



2015-11-09 02:31:26 Error: [Cake\Error\FatalErrorException] Call to a member function newEntity() on boolean
Request URL: /cakephp-3-1-1/personal-details/add
Stack Trace:
#0 C:\xampp\htdocs\cakephp-3-1-1\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(90): Cake\Error\BaseErrorHandler->handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 48)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2015-11-09 03:34:41 Error: Fatal Error (1): Call to a member function format() on null in [C:\xampp\htdocs\cakephp-3-1-1\src\Template\Orderpizza\index.ctp, line 25]
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 191
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 90
[main] - [internal], line ??



2015-11-09 03:34:41 Error: [Cake\Error\FatalErrorException] Call to a member function format() on null
Request URL: /cakephp-3-1-1/orderpizza
Stack Trace:
#0 C:\xampp\htdocs\cakephp-3-1-1\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(90): Cake\Error\BaseErrorHandler->handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 25)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2015-11-09 03:34:53 Error: Fatal Error (1): Call to a member function format() on null in [C:\xampp\htdocs\cakephp-3-1-1\src\Template\Orderpizza\index.ctp, line 25]
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 191
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 90
[main] - [internal], line ??



2015-11-09 03:34:53 Error: [Cake\Error\FatalErrorException] Call to a member function format() on null
Request URL: /cakephp-3-1-1/orderpizza
Stack Trace:
#0 C:\xampp\htdocs\cakephp-3-1-1\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(90): Cake\Error\BaseErrorHandler->handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 25)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2015-11-09 03:34:57 Error: Fatal Error (1): Call to a member function format() on null in [C:\xampp\htdocs\cakephp-3-1-1\src\Template\Orderpizza\index.ctp, line 25]
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 191
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 90
[main] - [internal], line ??



2015-11-09 03:34:57 Error: [Cake\Error\FatalErrorException] Call to a member function format() on null
Request URL: /cakephp-3-1-1/orderpizza
Stack Trace:
#0 C:\xampp\htdocs\cakephp-3-1-1\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(90): Cake\Error\BaseErrorHandler->handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 25)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2015-11-09 03:58:30 Error: [BadMethodCallException] Unknown method "set"
Request URL: /cakephp-3-1-1/orderpizza/add
Stack Trace:
#0 C:\xampp\htdocs\cakephp-3-1-1\src\Controller\OrderpizzaController.php(53): Cake\ORM\Table->__call('set', Array)
#1 C:\xampp\htdocs\cakephp-3-1-1\src\Controller\OrderpizzaController.php(53): App\Model\Table\OrderpizzaTable->set('toppings', 'jhjhj,hjhjjh,hj...')
#2 [internal function]: App\Controller\OrderpizzaController->add()
#3 C:\xampp\htdocs\cakephp-3-1-1\vendor\cakephp\cakephp\src\Controller\Controller.php(429): call_user_func_array(Array, Array)
#4 C:\xampp\htdocs\cakephp-3-1-1\vendor\cakephp\cakephp\src\Routing\Dispatcher.php(114): Cake\Controller\Controller->invokeAction()
#5 C:\xampp\htdocs\cakephp-3-1-1\vendor\cakephp\cakephp\src\Routing\Dispatcher.php(87): Cake\Routing\Dispatcher->_invoke(Object(App\Controller\OrderpizzaController))
#6 C:\xampp\htdocs\cakephp-3-1-1\webroot\index.php(37): Cake\Routing\Dispatcher->dispatch(Object(Cake\Network\Request), Object(Cake\Network\Response))
#7 {main}


2015-11-09 04:04:18 Error: [BadMethodCallException] Unknown method "set"
Request URL: /cakephp-3-1-1/orderpizza/add
Stack Trace:
#0 C:\xampp\htdocs\cakephp-3-1-1\src\Controller\OrderpizzaController.php(47): Cake\ORM\Table->__call('set', Array)
#1 C:\xampp\htdocs\cakephp-3-1-1\src\Controller\OrderpizzaController.php(47): App\Model\Table\OrderpizzaTable->set('toppings', 'jhjhj,hjhjjh,hj...')
#2 [internal function]: App\Controller\OrderpizzaController->add()
#3 C:\xampp\htdocs\cakephp-3-1-1\vendor\cakephp\cakephp\src\Controller\Controller.php(429): call_user_func_array(Array, Array)
#4 C:\xampp\htdocs\cakephp-3-1-1\vendor\cakephp\cakephp\src\Routing\Dispatcher.php(114): Cake\Controller\Controller->invokeAction()
#5 C:\xampp\htdocs\cakephp-3-1-1\vendor\cakephp\cakephp\src\Routing\Dispatcher.php(87): Cake\Routing\Dispatcher->_invoke(Object(App\Controller\OrderpizzaController))
#6 C:\xampp\htdocs\cakephp-3-1-1\webroot\index.php(37): Cake\Routing\Dispatcher->dispatch(Object(Cake\Network\Request), Object(Cake\Network\Response))
#7 {main}


2015-11-09 04:04:23 Error: [BadMethodCallException] Unknown method "set"
Request URL: /cakephp-3-1-1/orderpizza/add
Stack Trace:
#0 C:\xampp\htdocs\cakephp-3-1-1\src\Controller\OrderpizzaController.php(47): Cake\ORM\Table->__call('set', Array)
#1 C:\xampp\htdocs\cakephp-3-1-1\src\Controller\OrderpizzaController.php(47): App\Model\Table\OrderpizzaTable->set('toppings', 'jhjhj,hjhjjh,hj...')
#2 [internal function]: App\Controller\OrderpizzaController->add()
#3 C:\xampp\htdocs\cakephp-3-1-1\vendor\cakephp\cakephp\src\Controller\Controller.php(429): call_user_func_array(Array, Array)
#4 C:\xampp\htdocs\cakephp-3-1-1\vendor\cakephp\cakephp\src\Routing\Dispatcher.php(114): Cake\Controller\Controller->invokeAction()
#5 C:\xampp\htdocs\cakephp-3-1-1\vendor\cakephp\cakephp\src\Routing\Dispatcher.php(87): Cake\Routing\Dispatcher->_invoke(Object(App\Controller\OrderpizzaController))
#6 C:\xampp\htdocs\cakephp-3-1-1\webroot\index.php(37): Cake\Routing\Dispatcher->dispatch(Object(Cake\Network\Request), Object(Cake\Network\Response))
#7 {main}


2015-11-09 04:05:00 Error: [BadMethodCallException] Unknown method "set"
Request URL: /cakephp-3-1-1/orderpizza/add
Stack Trace:
#0 C:\xampp\htdocs\cakephp-3-1-1\src\Controller\OrderpizzaController.php(47): Cake\ORM\Table->__call('set', Array)
#1 C:\xampp\htdocs\cakephp-3-1-1\src\Controller\OrderpizzaController.php(47): App\Model\Table\OrderpizzaTable->set('toppings', 'jhjhj,hjhjjh,hj...')
#2 [internal function]: App\Controller\OrderpizzaController->add()
#3 C:\xampp\htdocs\cakephp-3-1-1\vendor\cakephp\cakephp\src\Controller\Controller.php(429): call_user_func_array(Array, Array)
#4 C:\xampp\htdocs\cakephp-3-1-1\vendor\cakephp\cakephp\src\Routing\Dispatcher.php(114): Cake\Controller\Controller->invokeAction()
#5 C:\xampp\htdocs\cakephp-3-1-1\vendor\cakephp\cakephp\src\Routing\Dispatcher.php(87): Cake\Routing\Dispatcher->_invoke(Object(App\Controller\OrderpizzaController))
#6 C:\xampp\htdocs\cakephp-3-1-1\webroot\index.php(37): Cake\Routing\Dispatcher->dispatch(Object(Cake\Network\Request), Object(Cake\Network\Response))
#7 {main}


2015-11-09 04:09:30 Error: Fatal Error (1): Call to undefined method Cake\ORM\Entity::data() in [C:\xampp\htdocs\cakephp-3-1-1\src\Controller\OrderpizzaController.php, line 48]
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 191
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 90
[main] - [internal], line ??



2015-11-09 04:09:30 Error: [Cake\Error\FatalErrorException] Call to undefined method Cake\ORM\Entity::data()
Request URL: /cakephp-3-1-1/orderpizza/add
Stack Trace:
#0 C:\xampp\htdocs\cakephp-3-1-1\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(90): Cake\Error\BaseErrorHandler->handleFatalError(1, 'Call to undefin...', 'C:\\xampp\\htdocs...', 48)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2015-11-09 04:26:23 Warning: Warning (2): Invalid argument supplied for foreach() in [C:\xampp\htdocs\cakephp-3-1-1\src\Controller\OrderpizzaController.php, line 49]
Trace:
Cake\Error\BaseErrorHandler::handleError() - CORE\src\Error\BaseErrorHandler.php, line 138
App\Controller\OrderpizzaController::add() - APP/Controller\OrderpizzaController.php, line 49
Cake\Controller\Controller::invokeAction() - CORE\src\Controller\Controller.php, line 429
Cake\Routing\Dispatcher::_invoke() - CORE\src\Routing\Dispatcher.php, line 114
Cake\Routing\Dispatcher::dispatch() - CORE\src\Routing\Dispatcher.php, line 87
[main] - ROOT\webroot\index.php, line 37



2015-11-09 04:26:24 Error: [PDOException] SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'toppings' cannot be null
Request URL: /cakephp-3-1-1/orderpizza/add
Stack Trace:
#0 C:\xampp\htdocs\cakephp-3-1-1\vendor\cakephp\cakephp\src\Database\Statement\MysqlStatement.php(36): PDOStatement->execute(NULL)
#1 C:\xampp\htdocs\cakephp-3-1-1\vendor\cakephp\cakephp\src\Database\Statement\StatementDecorator.php(171): Cake\Database\Statement\MysqlStatement->execute(NULL)
#2 C:\xampp\htdocs\cakephp-3-1-1\vendor\cakephp\cakephp\src\Database\Log\LoggingStatement.php(56): Cake\Database\Statement\StatementDecorator->execute(NULL)
#3 C:\xampp\htdocs\cakephp-3-1-1\vendor\cakephp\cakephp\src\Database\Connection.php(270): Cake\Database\Log\LoggingStatement->execute()
#4 C:\xampp\htdocs\cakephp-3-1-1\vendor\cakephp\cakephp\src\Database\Query.php(174): Cake\Database\Connection->run(Object(Cake\ORM\Query))
#5 C:\xampp\htdocs\cakephp-3-1-1\vendor\cakephp\cakephp\src\ORM\Table.php(1530): Cake\Database\Query->execute()
#6 C:\xampp\htdocs\cakephp-3-1-1\vendor\cakephp\cakephp\src\ORM\Table.php(1446): Cake\ORM\Table->_insert(Object(Cake\ORM\Entity), Array)
#7 C:\xampp\htdocs\cakephp-3-1-1\vendor\cakephp\cakephp\src\ORM\Table.php(1377): Cake\ORM\Table->_processSave(Object(Cake\ORM\Entity), Object(ArrayObject))
#8 C:\xampp\htdocs\cakephp-3-1-1\vendor\cakephp\cakephp\src\Database\Connection.php(546): Cake\ORM\Table->Cake\ORM\{closure}(Object(Cake\Database\Connection))
#9 C:\xampp\htdocs\cakephp-3-1-1\vendor\cakephp\cakephp\src\ORM\Table.php(1378): Cake\Database\Connection->transactional(Object(Closure))
#10 C:\xampp\htdocs\cakephp-3-1-1\src\Controller\OrderpizzaController.php(59): Cake\ORM\Table->save(Object(Cake\ORM\Entity))
#11 [internal function]: App\Controller\OrderpizzaController->add()
#12 C:\xampp\htdocs\cakephp-3-1-1\vendor\cakephp\cakephp\src\Controller\Controller.php(429): call_user_func_array(Array, Array)
#13 C:\xampp\htdocs\cakephp-3-1-1\vendor\cakephp\cakephp\src\Routing\Dispatcher.php(114): Cake\Controller\Controller->invokeAction()
#14 C:\xampp\htdocs\cakephp-3-1-1\vendor\cakephp\cakephp\src\Routing\Dispatcher.php(87): Cake\Routing\Dispatcher->_invoke(Object(App\Controller\OrderpizzaController))
#15 C:\xampp\htdocs\cakephp-3-1-1\webroot\index.php(37): Cake\Routing\Dispatcher->dispatch(Object(Cake\Network\Request), Object(Cake\Network\Response))
#16 {main}


2015-11-09 04:27:11 Warning: Warning (2): Invalid argument supplied for foreach() in [C:\xampp\htdocs\cakephp-3-1-1\src\Controller\OrderpizzaController.php, line 49]
Trace:
Cake\Error\BaseErrorHandler::handleError() - CORE\src\Error\BaseErrorHandler.php, line 138
App\Controller\OrderpizzaController::add() - APP/Controller\OrderpizzaController.php, line 49
Cake\Controller\Controller::invokeAction() - CORE\src\Controller\Controller.php, line 429
Cake\Routing\Dispatcher::_invoke() - CORE\src\Routing\Dispatcher.php, line 114
Cake\Routing\Dispatcher::dispatch() - CORE\src\Routing\Dispatcher.php, line 87
[main] - ROOT\webroot\index.php, line 37



2015-11-09 04:27:11 Error: [PDOException] SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'toppings' cannot be null
Request URL: /cakephp-3-1-1/orderpizza/add
Stack Trace:
#0 C:\xampp\htdocs\cakephp-3-1-1\vendor\cakephp\cakephp\src\Database\Statement\MysqlStatement.php(36): PDOStatement->execute(NULL)
#1 C:\xampp\htdocs\cakephp-3-1-1\vendor\cakephp\cakephp\src\Database\Statement\StatementDecorator.php(171): Cake\Database\Statement\MysqlStatement->execute(NULL)
#2 C:\xampp\htdocs\cakephp-3-1-1\vendor\cakephp\cakephp\src\Database\Log\LoggingStatement.php(56): Cake\Database\Statement\StatementDecorator->execute(NULL)
#3 C:\xampp\htdocs\cakephp-3-1-1\vendor\cakephp\cakephp\src\Database\Connection.php(270): Cake\Database\Log\LoggingStatement->execute()
#4 C:\xampp\htdocs\cakephp-3-1-1\vendor\cakephp\cakephp\src\Database\Query.php(174): Cake\Database\Connection->run(Object(Cake\ORM\Query))
#5 C:\xampp\htdocs\cakephp-3-1-1\vendor\cakephp\cakephp\src\ORM\Table.php(1530): Cake\Database\Query->execute()
#6 C:\xampp\htdocs\cakephp-3-1-1\vendor\cakephp\cakephp\src\ORM\Table.php(1446): Cake\ORM\Table->_insert(Object(Cake\ORM\Entity), Array)
#7 C:\xampp\htdocs\cakephp-3-1-1\vendor\cakephp\cakephp\src\ORM\Table.php(1377): Cake\ORM\Table->_processSave(Object(Cake\ORM\Entity), Object(ArrayObject))
#8 C:\xampp\htdocs\cakephp-3-1-1\vendor\cakephp\cakephp\src\Database\Connection.php(546): Cake\ORM\Table->Cake\ORM\{closure}(Object(Cake\Database\Connection))
#9 C:\xampp\htdocs\cakephp-3-1-1\vendor\cakephp\cakephp\src\ORM\Table.php(1378): Cake\Database\Connection->transactional(Object(Closure))
#10 C:\xampp\htdocs\cakephp-3-1-1\src\Controller\OrderpizzaController.php(59): Cake\ORM\Table->save(Object(Cake\ORM\Entity))
#11 [internal function]: App\Controller\OrderpizzaController->add()
#12 C:\xampp\htdocs\cakephp-3-1-1\vendor\cakephp\cakephp\src\Controller\Controller.php(429): call_user_func_array(Array, Array)
#13 C:\xampp\htdocs\cakephp-3-1-1\vendor\cakephp\cakephp\src\Routing\Dispatcher.php(114): Cake\Controller\Controller->invokeAction()
#14 C:\xampp\htdocs\cakephp-3-1-1\vendor\cakephp\cakephp\src\Routing\Dispatcher.php(87): Cake\Routing\Dispatcher->_invoke(Object(App\Controller\OrderpizzaController))
#15 C:\xampp\htdocs\cakephp-3-1-1\webroot\index.php(37): Cake\Routing\Dispatcher->dispatch(Object(Cake\Network\Request), Object(Cake\Network\Response))
#16 {main}


2015-11-09 04:27:16 Warning: Warning (2): Invalid argument supplied for foreach() in [C:\xampp\htdocs\cakephp-3-1-1\src\Controller\OrderpizzaController.php, line 49]
Trace:
Cake\Error\BaseErrorHandler::handleError() - CORE\src\Error\BaseErrorHandler.php, line 138
App\Controller\OrderpizzaController::add() - APP/Controller\OrderpizzaController.php, line 49
Cake\Controller\Controller::invokeAction() - CORE\src\Controller\Controller.php, line 429
Cake\Routing\Dispatcher::_invoke() - CORE\src\Routing\Dispatcher.php, line 114
Cake\Routing\Dispatcher::dispatch() - CORE\src\Routing\Dispatcher.php, line 87
[main] - ROOT\webroot\index.php, line 37



2015-11-09 04:27:17 Error: [PDOException] SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'toppings' cannot be null
Request URL: /cakephp-3-1-1/orderpizza/add
Stack Trace:
#0 C:\xampp\htdocs\cakephp-3-1-1\vendor\cakephp\cakephp\src\Database\Statement\MysqlStatement.php(36): PDOStatement->execute(NULL)
#1 C:\xampp\htdocs\cakephp-3-1-1\vendor\cakephp\cakephp\src\Database\Statement\StatementDecorator.php(171): Cake\Database\Statement\MysqlStatement->execute(NULL)
#2 C:\xampp\htdocs\cakephp-3-1-1\vendor\cakephp\cakephp\src\Database\Log\LoggingStatement.php(56): Cake\Database\Statement\StatementDecorator->execute(NULL)
#3 C:\xampp\htdocs\cakephp-3-1-1\vendor\cakephp\cakephp\src\Database\Connection.php(270): Cake\Database\Log\LoggingStatement->execute()
#4 C:\xampp\htdocs\cakephp-3-1-1\vendor\cakephp\cakephp\src\Database\Query.php(174): Cake\Database\Connection->run(Object(Cake\ORM\Query))
#5 C:\xampp\htdocs\cakephp-3-1-1\vendor\cakephp\cakephp\src\ORM\Table.php(1530): Cake\Database\Query->execute()
#6 C:\xampp\htdocs\cakephp-3-1-1\vendor\cakephp\cakephp\src\ORM\Table.php(1446): Cake\ORM\Table->_insert(Object(Cake\ORM\Entity), Array)
#7 C:\xampp\htdocs\cakephp-3-1-1\vendor\cakephp\cakephp\src\ORM\Table.php(1377): Cake\ORM\Table->_processSave(Object(Cake\ORM\Entity), Object(ArrayObject))
#8 C:\xampp\htdocs\cakephp-3-1-1\vendor\cakephp\cakephp\src\Database\Connection.php(546): Cake\ORM\Table->Cake\ORM\{closure}(Object(Cake\Database\Connection))
#9 C:\xampp\htdocs\cakephp-3-1-1\vendor\cakephp\cakephp\src\ORM\Table.php(1378): Cake\Database\Connection->transactional(Object(Closure))
#10 C:\xampp\htdocs\cakephp-3-1-1\src\Controller\OrderpizzaController.php(59): Cake\ORM\Table->save(Object(Cake\ORM\Entity))
#11 [internal function]: App\Controller\OrderpizzaController->add()
#12 C:\xampp\htdocs\cakephp-3-1-1\vendor\cakephp\cakephp\src\Controller\Controller.php(429): call_user_func_array(Array, Array)
#13 C:\xampp\htdocs\cakephp-3-1-1\vendor\cakephp\cakephp\src\Routing\Dispatcher.php(114): Cake\Controller\Controller->invokeAction()
#14 C:\xampp\htdocs\cakephp-3-1-1\vendor\cakephp\cakephp\src\Routing\Dispatcher.php(87): Cake\Routing\Dispatcher->_invoke(Object(App\Controller\OrderpizzaController))
#15 C:\xampp\htdocs\cakephp-3-1-1\webroot\index.php(37): Cake\Routing\Dispatcher->dispatch(Object(Cake\Network\Request), Object(Cake\Network\Response))
#16 {main}


2015-11-09 04:29:21 Error: [PDOException] SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'toppings' cannot be null
Request URL: /cakephp-3-1-1/orderpizza/add
Stack Trace:
#0 C:\xampp\htdocs\cakephp-3-1-1\vendor\cakephp\cakephp\src\Database\Statement\MysqlStatement.php(36): PDOStatement->execute(NULL)
#1 C:\xampp\htdocs\cakephp-3-1-1\vendor\cakephp\cakephp\src\Database\Statement\StatementDecorator.php(171): Cake\Database\Statement\MysqlStatement->execute(NULL)
#2 C:\xampp\htdocs\cakephp-3-1-1\vendor\cakephp\cakephp\src\Database\Log\LoggingStatement.php(56): Cake\Database\Statement\StatementDecorator->execute(NULL)
#3 C:\xampp\htdocs\cakephp-3-1-1\vendor\cakephp\cakephp\src\Database\Connection.php(270): Cake\Database\Log\LoggingStatement->execute()
#4 C:\xampp\htdocs\cakephp-3-1-1\vendor\cakephp\cakephp\src\Database\Query.php(174): Cake\Database\Connection->run(Object(Cake\ORM\Query))
#5 C:\xampp\htdocs\cakephp-3-1-1\vendor\cakephp\cakephp\src\ORM\Table.php(1530): Cake\Database\Query->execute()
#6 C:\xampp\htdocs\cakephp-3-1-1\vendor\cakephp\cakephp\src\ORM\Table.php(1446): Cake\ORM\Table->_insert(Object(Cake\ORM\Entity), Array)
#7 C:\xampp\htdocs\cakephp-3-1-1\vendor\cakephp\cakephp\src\ORM\Table.php(1377): Cake\ORM\Table->_processSave(Object(Cake\ORM\Entity), Object(ArrayObject))
#8 C:\xampp\htdocs\cakephp-3-1-1\vendor\cakephp\cakephp\src\Database\Connection.php(546): Cake\ORM\Table->Cake\ORM\{closure}(Object(Cake\Database\Connection))
#9 C:\xampp\htdocs\cakephp-3-1-1\vendor\cakephp\cakephp\src\ORM\Table.php(1378): Cake\Database\Connection->transactional(Object(Closure))
#10 C:\xampp\htdocs\cakephp-3-1-1\src\Controller\OrderpizzaController.php(57): Cake\ORM\Table->save(Object(Cake\ORM\Entity))
#11 [internal function]: App\Controller\OrderpizzaController->add()
#12 C:\xampp\htdocs\cakephp-3-1-1\vendor\cakephp\cakephp\src\Controller\Controller.php(429): call_user_func_array(Array, Array)
#13 C:\xampp\htdocs\cakephp-3-1-1\vendor\cakephp\cakephp\src\Routing\Dispatcher.php(114): Cake\Controller\Controller->invokeAction()
#14 C:\xampp\htdocs\cakephp-3-1-1\vendor\cakephp\cakephp\src\Routing\Dispatcher.php(87): Cake\Routing\Dispatcher->_invoke(Object(App\Controller\OrderpizzaController))
#15 C:\xampp\htdocs\cakephp-3-1-1\webroot\index.php(37): Cake\Routing\Dispatcher->dispatch(Object(Cake\Network\Request), Object(Cake\Network\Response))
#16 {main}


2015-11-09 04:39:51 Error: [PDOException] SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'toppings' cannot be null
Request URL: /cakephp-3-1-1/orderpizza/add
Stack Trace:
#0 C:\xampp\htdocs\cakephp-3-1-1\vendor\cakephp\cakephp\src\Database\Statement\MysqlStatement.php(36): PDOStatement->execute(NULL)
#1 C:\xampp\htdocs\cakephp-3-1-1\vendor\cakephp\cakephp\src\Database\Statement\StatementDecorator.php(171): Cake\Database\Statement\MysqlStatement->execute(NULL)
#2 C:\xampp\htdocs\cakephp-3-1-1\vendor\cakephp\cakephp\src\Database\Log\LoggingStatement.php(56): Cake\Database\Statement\StatementDecorator->execute(NULL)
#3 C:\xampp\htdocs\cakephp-3-1-1\vendor\cakephp\cakephp\src\Database\Connection.php(270): Cake\Database\Log\LoggingStatement->execute()
#4 C:\xampp\htdocs\cakephp-3-1-1\vendor\cakephp\cakephp\src\Database\Query.php(174): Cake\Database\Connection->run(Object(Cake\ORM\Query))
#5 C:\xampp\htdocs\cakephp-3-1-1\vendor\cakephp\cakephp\src\ORM\Table.php(1530): Cake\Database\Query->execute()
#6 C:\xampp\htdocs\cakephp-3-1-1\vendor\cakephp\cakephp\src\ORM\Table.php(1446): Cake\ORM\Table->_insert(Object(Cake\ORM\Entity), Array)
#7 C:\xampp\htdocs\cakephp-3-1-1\vendor\cakephp\cakephp\src\ORM\Table.php(1377): Cake\ORM\Table->_processSave(Object(Cake\ORM\Entity), Object(ArrayObject))
#8 C:\xampp\htdocs\cakephp-3-1-1\vendor\cakephp\cakephp\src\Database\Connection.php(546): Cake\ORM\Table->Cake\ORM\{closure}(Object(Cake\Database\Connection))
#9 C:\xampp\htdocs\cakephp-3-1-1\vendor\cakephp\cakephp\src\ORM\Table.php(1378): Cake\Database\Connection->transactional(Object(Closure))
#10 C:\xampp\htdocs\cakephp-3-1-1\src\Controller\OrderpizzaController.php(60): Cake\ORM\Table->save(Object(Cake\ORM\Entity))
#11 [internal function]: App\Controller\OrderpizzaController->add()
#12 C:\xampp\htdocs\cakephp-3-1-1\vendor\cakephp\cakephp\src\Controller\Controller.php(429): call_user_func_array(Array, Array)
#13 C:\xampp\htdocs\cakephp-3-1-1\vendor\cakephp\cakephp\src\Routing\Dispatcher.php(114): Cake\Controller\Controller->invokeAction()
#14 C:\xampp\htdocs\cakephp-3-1-1\vendor\cakephp\cakephp\src\Routing\Dispatcher.php(87): Cake\Routing\Dispatcher->_invoke(Object(App\Controller\OrderpizzaController))
#15 C:\xampp\htdocs\cakephp-3-1-1\webroot\index.php(37): Cake\Routing\Dispatcher->dispatch(Object(Cake\Network\Request), Object(Cake\Network\Response))
#16 {main}


2015-11-09 04:40:11 Warning: Warning (2): implode(): Invalid arguments passed in [C:\xampp\htdocs\cakephp-3-1-1\src\Controller\OrderpizzaController.php, line 48]
Trace:
Cake\Error\BaseErrorHandler::handleError() - CORE\src\Error\BaseErrorHandler.php, line 138
implode - [internal], line ??
App\Controller\OrderpizzaController::add() - APP/Controller\OrderpizzaController.php, line 48
Cake\Controller\Controller::invokeAction() - CORE\src\Controller\Controller.php, line 429
Cake\Routing\Dispatcher::_invoke() - CORE\src\Routing\Dispatcher.php, line 114
Cake\Routing\Dispatcher::dispatch() - CORE\src\Routing\Dispatcher.php, line 87
[main] - ROOT\webroot\index.php, line 37



2015-11-09 04:40:11 Error: [PDOException] SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'toppings' cannot be null
Request URL: /cakephp-3-1-1/orderpizza/add
Stack Trace:
#0 C:\xampp\htdocs\cakephp-3-1-1\vendor\cakephp\cakephp\src\Database\Statement\MysqlStatement.php(36): PDOStatement->execute(NULL)
#1 C:\xampp\htdocs\cakephp-3-1-1\vendor\cakephp\cakephp\src\Database\Statement\StatementDecorator.php(171): Cake\Database\Statement\MysqlStatement->execute(NULL)
#2 C:\xampp\htdocs\cakephp-3-1-1\vendor\cakephp\cakephp\src\Database\Log\LoggingStatement.php(56): Cake\Database\Statement\StatementDecorator->execute(NULL)
#3 C:\xampp\htdocs\cakephp-3-1-1\vendor\cakephp\cakephp\src\Database\Connection.php(270): Cake\Database\Log\LoggingStatement->execute()
#4 C:\xampp\htdocs\cakephp-3-1-1\vendor\cakephp\cakephp\src\Database\Query.php(174): Cake\Database\Connection->run(Object(Cake\ORM\Query))
#5 C:\xampp\htdocs\cakephp-3-1-1\vendor\cakephp\cakephp\src\ORM\Table.php(1530): Cake\Database\Query->execute()
#6 C:\xampp\htdocs\cakephp-3-1-1\vendor\cakephp\cakephp\src\ORM\Table.php(1446): Cake\ORM\Table->_insert(Object(Cake\ORM\Entity), Array)
#7 C:\xampp\htdocs\cakephp-3-1-1\vendor\cakephp\cakephp\src\ORM\Table.php(1377): Cake\ORM\Table->_processSave(Object(Cake\ORM\Entity), Object(ArrayObject))
#8 C:\xampp\htdocs\cakephp-3-1-1\vendor\cakephp\cakephp\src\Database\Connection.php(546): Cake\ORM\Table->Cake\ORM\{closure}(Object(Cake\Database\Connection))
#9 C:\xampp\htdocs\cakephp-3-1-1\vendor\cakephp\cakephp\src\ORM\Table.php(1378): Cake\Database\Connection->transactional(Object(Closure))
#10 C:\xampp\htdocs\cakephp-3-1-1\src\Controller\OrderpizzaController.php(60): Cake\ORM\Table->save(Object(Cake\ORM\Entity))
#11 [internal function]: App\Controller\OrderpizzaController->add()
#12 C:\xampp\htdocs\cakephp-3-1-1\vendor\cakephp\cakephp\src\Controller\Controller.php(429): call_user_func_array(Array, Array)
#13 C:\xampp\htdocs\cakephp-3-1-1\vendor\cakephp\cakephp\src\Routing\Dispatcher.php(114): Cake\Controller\Controller->invokeAction()
#14 C:\xampp\htdocs\cakephp-3-1-1\vendor\cakephp\cakephp\src\Routing\Dispatcher.php(87): Cake\Routing\Dispatcher->_invoke(Object(App\Controller\OrderpizzaController))
#15 C:\xampp\htdocs\cakephp-3-1-1\webroot\index.php(37): Cake\Routing\Dispatcher->dispatch(Object(Cake\Network\Request), Object(Cake\Network\Response))
#16 {main}


2015-11-09 04:40:15 Warning: Warning (2): implode(): Invalid arguments passed in [C:\xampp\htdocs\cakephp-3-1-1\src\Controller\OrderpizzaController.php, line 48]
Trace:
Cake\Error\BaseErrorHandler::handleError() - CORE\src\Error\BaseErrorHandler.php, line 138
implode - [internal], line ??
App\Controller\OrderpizzaController::add() - APP/Controller\OrderpizzaController.php, line 48
Cake\Controller\Controller::invokeAction() - CORE\src\Controller\Controller.php, line 429
Cake\Routing\Dispatcher::_invoke() - CORE\src\Routing\Dispatcher.php, line 114
Cake\Routing\Dispatcher::dispatch() - CORE\src\Routing\Dispatcher.php, line 87
[main] - ROOT\webroot\index.php, line 37



2015-11-09 04:40:15 Error: [PDOException] SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'toppings' cannot be null
Request URL: /cakephp-3-1-1/orderpizza/add
Stack Trace:
#0 C:\xampp\htdocs\cakephp-3-1-1\vendor\cakephp\cakephp\src\Database\Statement\MysqlStatement.php(36): PDOStatement->execute(NULL)
#1 C:\xampp\htdocs\cakephp-3-1-1\vendor\cakephp\cakephp\src\Database\Statement\StatementDecorator.php(171): Cake\Database\Statement\MysqlStatement->execute(NULL)
#2 C:\xampp\htdocs\cakephp-3-1-1\vendor\cakephp\cakephp\src\Database\Log\LoggingStatement.php(56): Cake\Database\Statement\StatementDecorator->execute(NULL)
#3 C:\xampp\htdocs\cakephp-3-1-1\vendor\cakephp\cakephp\src\Database\Connection.php(270): Cake\Database\Log\LoggingStatement->execute()
#4 C:\xampp\htdocs\cakephp-3-1-1\vendor\cakephp\cakephp\src\Database\Query.php(174): Cake\Database\Connection->run(Object(Cake\ORM\Query))
#5 C:\xampp\htdocs\cakephp-3-1-1\vendor\cakephp\cakephp\src\ORM\Table.php(1530): Cake\Database\Query->execute()
#6 C:\xampp\htdocs\cakephp-3-1-1\vendor\cakephp\cakephp\src\ORM\Table.php(1446): Cake\ORM\Table->_insert(Object(Cake\ORM\Entity), Array)
#7 C:\xampp\htdocs\cakephp-3-1-1\vendor\cakephp\cakephp\src\ORM\Table.php(1377): Cake\ORM\Table->_processSave(Object(Cake\ORM\Entity), Object(ArrayObject))
#8 C:\xampp\htdocs\cakephp-3-1-1\vendor\cakephp\cakephp\src\Database\Connection.php(546): Cake\ORM\Table->Cake\ORM\{closure}(Object(Cake\Database\Connection))
#9 C:\xampp\htdocs\cakephp-3-1-1\vendor\cakephp\cakephp\src\ORM\Table.php(1378): Cake\Database\Connection->transactional(Object(Closure))
#10 C:\xampp\htdocs\cakephp-3-1-1\src\Controller\OrderpizzaController.php(60): Cake\ORM\Table->save(Object(Cake\ORM\Entity))
#11 [internal function]: App\Controller\OrderpizzaController->add()
#12 C:\xampp\htdocs\cakephp-3-1-1\vendor\cakephp\cakephp\src\Controller\Controller.php(429): call_user_func_array(Array, Array)
#13 C:\xampp\htdocs\cakephp-3-1-1\vendor\cakephp\cakephp\src\Routing\Dispatcher.php(114): Cake\Controller\Controller->invokeAction()
#14 C:\xampp\htdocs\cakephp-3-1-1\vendor\cakephp\cakephp\src\Routing\Dispatcher.php(87): Cake\Routing\Dispatcher->_invoke(Object(App\Controller\OrderpizzaController))
#15 C:\xampp\htdocs\cakephp-3-1-1\webroot\index.php(37): Cake\Routing\Dispatcher->dispatch(Object(Cake\Network\Request), Object(Cake\Network\Response))
#16 {main}


2015-11-09 04:41:26 Error: Fatal Error (1): Call to a member function get() on array in [C:\xampp\htdocs\cakephp-3-1-1\src\Controller\OrderpizzaController.php, line 47]
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 191
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 90
[main] - [internal], line ??



2015-11-09 04:41:26 Error: [Cake\Error\FatalErrorException] Call to a member function get() on array
Request URL: /cakephp-3-1-1/orderpizza/add
Stack Trace:
#0 C:\xampp\htdocs\cakephp-3-1-1\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(90): Cake\Error\BaseErrorHandler->handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 47)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2015-11-09 04:42:24 Error: Fatal Error (1): Call to a member function get() on array in [C:\xampp\htdocs\cakephp-3-1-1\src\Controller\OrderpizzaController.php, line 47]
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 191
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 90
[main] - [internal], line ??



2015-11-09 04:42:25 Error: [Cake\Error\FatalErrorException] Call to a member function get() on array
Request URL: /cakephp-3-1-1/orderpizza/add
Stack Trace:
#0 C:\xampp\htdocs\cakephp-3-1-1\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(90): Cake\Error\BaseErrorHandler->handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 47)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2015-11-09 04:43:19 Error: Fatal Error (1): Call to a member function array() on array in [C:\xampp\htdocs\cakephp-3-1-1\src\Controller\OrderpizzaController.php, line 47]
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 191
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 90
[main] - [internal], line ??



2015-11-09 04:43:20 Error: [Cake\Error\FatalErrorException] Call to a member function array() on array
Request URL: /cakephp-3-1-1/orderpizza/add
Stack Trace:
#0 C:\xampp\htdocs\cakephp-3-1-1\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(90): Cake\Error\BaseErrorHandler->handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 47)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2015-11-09 04:49:02 Error: [PDOException] SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'toppings' cannot be null
Request URL: /cakephp-3-1-1/orderpizza/add
Stack Trace:
#0 C:\xampp\htdocs\cakephp-3-1-1\vendor\cakephp\cakephp\src\Database\Statement\MysqlStatement.php(36): PDOStatement->execute(NULL)
#1 C:\xampp\htdocs\cakephp-3-1-1\vendor\cakephp\cakephp\src\Database\Statement\StatementDecorator.php(171): Cake\Database\Statement\MysqlStatement->execute(NULL)
#2 C:\xampp\htdocs\cakephp-3-1-1\vendor\cakephp\cakephp\src\Database\Log\LoggingStatement.php(56): Cake\Database\Statement\StatementDecorator->execute(NULL)
#3 C:\xampp\htdocs\cakephp-3-1-1\vendor\cakephp\cakephp\src\Database\Connection.php(270): Cake\Database\Log\LoggingStatement->execute()
#4 C:\xampp\htdocs\cakephp-3-1-1\vendor\cakephp\cakephp\src\Database\Query.php(174): Cake\Database\Connection->run(Object(Cake\ORM\Query))
#5 C:\xampp\htdocs\cakephp-3-1-1\vendor\cakephp\cakephp\src\ORM\Table.php(1530): Cake\Database\Query->execute()
#6 C:\xampp\htdocs\cakephp-3-1-1\vendor\cakephp\cakephp\src\ORM\Table.php(1446): Cake\ORM\Table->_insert(Object(Cake\ORM\Entity), Array)
#7 C:\xampp\htdocs\cakephp-3-1-1\vendor\cakephp\cakephp\src\ORM\Table.php(1377): Cake\ORM\Table->_processSave(Object(Cake\ORM\Entity), Object(ArrayObject))
#8 C:\xampp\htdocs\cakephp-3-1-1\vendor\cakephp\cakephp\src\Database\Connection.php(546): Cake\ORM\Table->Cake\ORM\{closure}(Object(Cake\Database\Connection))
#9 C:\xampp\htdocs\cakephp-3-1-1\vendor\cakephp\cakephp\src\ORM\Table.php(1378): Cake\Database\Connection->transactional(Object(Closure))
#10 C:\xampp\htdocs\cakephp-3-1-1\src\Controller\OrderpizzaController.php(60): Cake\ORM\Table->save(Object(Cake\ORM\Entity))
#11 [internal function]: App\Controller\OrderpizzaController->add()
#12 C:\xampp\htdocs\cakephp-3-1-1\vendor\cakephp\cakephp\src\Controller\Controller.php(429): call_user_func_array(Array, Array)
#13 C:\xampp\htdocs\cakephp-3-1-1\vendor\cakephp\cakephp\src\Routing\Dispatcher.php(114): Cake\Controller\Controller->invokeAction()
#14 C:\xampp\htdocs\cakephp-3-1-1\vendor\cakephp\cakephp\src\Routing\Dispatcher.php(87): Cake\Routing\Dispatcher->_invoke(Object(App\Controller\OrderpizzaController))
#15 C:\xampp\htdocs\cakephp-3-1-1\webroot\index.php(37): Cake\Routing\Dispatcher->dispatch(Object(Cake\Network\Request), Object(Cake\Network\Response))
#16 {main}


2015-11-09 04:51:12 Warning: Warning (2): implode(): Invalid arguments passed in [C:\xampp\htdocs\cakephp-3-1-1\src\Controller\OrderpizzaController.php, line 48]
Trace:
Cake\Error\BaseErrorHandler::handleError() - CORE\src\Error\BaseErrorHandler.php, line 138
implode - [internal], line ??
App\Controller\OrderpizzaController::add() - APP/Controller\OrderpizzaController.php, line 48
Cake\Controller\Controller::invokeAction() - CORE\src\Controller\Controller.php, line 429
Cake\Routing\Dispatcher::_invoke() - CORE\src\Routing\Dispatcher.php, line 114
Cake\Routing\Dispatcher::dispatch() - CORE\src\Routing\Dispatcher.php, line 87
[main] - ROOT\webroot\index.php, line 37



2015-11-09 04:51:12 Error: [PDOException] SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'toppings' cannot be null
Request URL: /cakephp-3-1-1/orderpizza/add
Stack Trace:
#0 C:\xampp\htdocs\cakephp-3-1-1\vendor\cakephp\cakephp\src\Database\Statement\MysqlStatement.php(36): PDOStatement->execute(NULL)
#1 C:\xampp\htdocs\cakephp-3-1-1\vendor\cakephp\cakephp\src\Database\Statement\StatementDecorator.php(171): Cake\Database\Statement\MysqlStatement->execute(NULL)
#2 C:\xampp\htdocs\cakephp-3-1-1\vendor\cakephp\cakephp\src\Database\Log\LoggingStatement.php(56): Cake\Database\Statement\StatementDecorator->execute(NULL)
#3 C:\xampp\htdocs\cakephp-3-1-1\vendor\cakephp\cakephp\src\Database\Connection.php(270): Cake\Database\Log\LoggingStatement->execute()
#4 C:\xampp\htdocs\cakephp-3-1-1\vendor\cakephp\cakephp\src\Database\Query.php(174): Cake\Database\Connection->run(Object(Cake\ORM\Query))
#5 C:\xampp\htdocs\cakephp-3-1-1\vendor\cakephp\cakephp\src\ORM\Table.php(1530): Cake\Database\Query->execute()
#6 C:\xampp\htdocs\cakephp-3-1-1\vendor\cakephp\cakephp\src\ORM\Table.php(1446): Cake\ORM\Table->_insert(Object(Cake\ORM\Entity), Array)
#7 C:\xampp\htdocs\cakephp-3-1-1\vendor\cakephp\cakephp\src\ORM\Table.php(1377): Cake\ORM\Table->_processSave(Object(Cake\ORM\Entity), Object(ArrayObject))
#8 C:\xampp\htdocs\cakephp-3-1-1\vendor\cakephp\cakephp\src\Database\Connection.php(546): Cake\ORM\Table->Cake\ORM\{closure}(Object(Cake\Database\Connection))
#9 C:\xampp\htdocs\cakephp-3-1-1\vendor\cakephp\cakephp\src\ORM\Table.php(1378): Cake\Database\Connection->transactional(Object(Closure))
#10 C:\xampp\htdocs\cakephp-3-1-1\src\Controller\OrderpizzaController.php(58): Cake\ORM\Table->save(Object(Cake\ORM\Entity))
#11 [internal function]: App\Controller\OrderpizzaController->add()
#12 C:\xampp\htdocs\cakephp-3-1-1\vendor\cakephp\cakephp\src\Controller\Controller.php(429): call_user_func_array(Array, Array)
#13 C:\xampp\htdocs\cakephp-3-1-1\vendor\cakephp\cakephp\src\Routing\Dispatcher.php(114): Cake\Controller\Controller->invokeAction()
#14 C:\xampp\htdocs\cakephp-3-1-1\vendor\cakephp\cakephp\src\Routing\Dispatcher.php(87): Cake\Routing\Dispatcher->_invoke(Object(App\Controller\OrderpizzaController))
#15 C:\xampp\htdocs\cakephp-3-1-1\webroot\index.php(37): Cake\Routing\Dispatcher->dispatch(Object(Cake\Network\Request), Object(Cake\Network\Response))
#16 {main}


2015-11-09 04:51:58 Warning: Warning (2): implode(): Invalid arguments passed in [C:\xampp\htdocs\cakephp-3-1-1\src\Controller\OrderpizzaController.php, line 48]
Trace:
Cake\Error\BaseErrorHandler::handleError() - CORE\src\Error\BaseErrorHandler.php, line 138
implode - [internal], line ??
App\Controller\OrderpizzaController::add() - APP/Controller\OrderpizzaController.php, line 48
Cake\Controller\Controller::invokeAction() - CORE\src\Controller\Controller.php, line 429
Cake\Routing\Dispatcher::_invoke() - CORE\src\Routing\Dispatcher.php, line 114
Cake\Routing\Dispatcher::dispatch() - CORE\src\Routing\Dispatcher.php, line 87
[main] - ROOT\webroot\index.php, line 37



2015-11-09 04:51:58 Error: [PDOException] SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'toppings' cannot be null
Request URL: /cakephp-3-1-1/orderpizza/add
Stack Trace:
#0 C:\xampp\htdocs\cakephp-3-1-1\vendor\cakephp\cakephp\src\Database\Statement\MysqlStatement.php(36): PDOStatement->execute(NULL)
#1 C:\xampp\htdocs\cakephp-3-1-1\vendor\cakephp\cakephp\src\Database\Statement\StatementDecorator.php(171): Cake\Database\Statement\MysqlStatement->execute(NULL)
#2 C:\xampp\htdocs\cakephp-3-1-1\vendor\cakephp\cakephp\src\Database\Log\LoggingStatement.php(56): Cake\Database\Statement\StatementDecorator->execute(NULL)
#3 C:\xampp\htdocs\cakephp-3-1-1\vendor\cakephp\cakephp\src\Database\Connection.php(270): Cake\Database\Log\LoggingStatement->execute()
#4 C:\xampp\htdocs\cakephp-3-1-1\vendor\cakephp\cakephp\src\Database\Query.php(174): Cake\Database\Connection->run(Object(Cake\ORM\Query))
#5 C:\xampp\htdocs\cakephp-3-1-1\vendor\cakephp\cakephp\src\ORM\Table.php(1530): Cake\Database\Query->execute()
#6 C:\xampp\htdocs\cakephp-3-1-1\vendor\cakephp\cakephp\src\ORM\Table.php(1446): Cake\ORM\Table->_insert(Object(Cake\ORM\Entity), Array)
#7 C:\xampp\htdocs\cakephp-3-1-1\vendor\cakephp\cakephp\src\ORM\Table.php(1377): Cake\ORM\Table->_processSave(Object(Cake\ORM\Entity), Object(ArrayObject))
#8 C:\xampp\htdocs\cakephp-3-1-1\vendor\cakephp\cakephp\src\Database\Connection.php(546): Cake\ORM\Table->Cake\ORM\{closure}(Object(Cake\Database\Connection))
#9 C:\xampp\htdocs\cakephp-3-1-1\vendor\cakephp\cakephp\src\ORM\Table.php(1378): Cake\Database\Connection->transactional(Object(Closure))
#10 C:\xampp\htdocs\cakephp-3-1-1\src\Controller\OrderpizzaController.php(58): Cake\ORM\Table->save(Object(Cake\ORM\Entity))
#11 [internal function]: App\Controller\OrderpizzaController->add()
#12 C:\xampp\htdocs\cakephp-3-1-1\vendor\cakephp\cakephp\src\Controller\Controller.php(429): call_user_func_array(Array, Array)
#13 C:\xampp\htdocs\cakephp-3-1-1\vendor\cakephp\cakephp\src\Routing\Dispatcher.php(114): Cake\Controller\Controller->invokeAction()
#14 C:\xampp\htdocs\cakephp-3-1-1\vendor\cakephp\cakephp\src\Routing\Dispatcher.php(87): Cake\Routing\Dispatcher->_invoke(Object(App\Controller\OrderpizzaController))
#15 C:\xampp\htdocs\cakephp-3-1-1\webroot\index.php(37): Cake\Routing\Dispatcher->dispatch(Object(Cake\Network\Request), Object(Cake\Network\Response))
#16 {main}


2015-11-09 04:52:15 Warning: Warning (2): implode(): Invalid arguments passed in [C:\xampp\htdocs\cakephp-3-1-1\src\Controller\OrderpizzaController.php, line 48]
Trace:
Cake\Error\BaseErrorHandler::handleError() - CORE\src\Error\BaseErrorHandler.php, line 138
implode - [internal], line ??
App\Controller\OrderpizzaController::add() - APP/Controller\OrderpizzaController.php, line 48
Cake\Controller\Controller::invokeAction() - CORE\src\Controller\Controller.php, line 429
Cake\Routing\Dispatcher::_invoke() - CORE\src\Routing\Dispatcher.php, line 114
Cake\Routing\Dispatcher::dispatch() - CORE\src\Routing\Dispatcher.php, line 87
[main] - ROOT\webroot\index.php, line 37



2015-11-09 04:52:16 Error: [PDOException] SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'toppings' cannot be null
Request URL: /cakephp-3-1-1/orderpizza/add
Stack Trace:
#0 C:\xampp\htdocs\cakephp-3-1-1\vendor\cakephp\cakephp\src\Database\Statement\MysqlStatement.php(36): PDOStatement->execute(NULL)
#1 C:\xampp\htdocs\cakephp-3-1-1\vendor\cakephp\cakephp\src\Database\Statement\StatementDecorator.php(171): Cake\Database\Statement\MysqlStatement->execute(NULL)
#2 C:\xampp\htdocs\cakephp-3-1-1\vendor\cakephp\cakephp\src\Database\Log\LoggingStatement.php(56): Cake\Database\Statement\StatementDecorator->execute(NULL)
#3 C:\xampp\htdocs\cakephp-3-1-1\vendor\cakephp\cakephp\src\Database\Connection.php(270): Cake\Database\Log\LoggingStatement->execute()
#4 C:\xampp\htdocs\cakephp-3-1-1\vendor\cakephp\cakephp\src\Database\Query.php(174): Cake\Database\Connection->run(Object(Cake\ORM\Query))
#5 C:\xampp\htdocs\cakephp-3-1-1\vendor\cakephp\cakephp\src\ORM\Table.php(1530): Cake\Database\Query->execute()
#6 C:\xampp\htdocs\cakephp-3-1-1\vendor\cakephp\cakephp\src\ORM\Table.php(1446): Cake\ORM\Table->_insert(Object(Cake\ORM\Entity), Array)
#7 C:\xampp\htdocs\cakephp-3-1-1\vendor\cakephp\cakephp\src\ORM\Table.php(1377): Cake\ORM\Table->_processSave(Object(Cake\ORM\Entity), Object(ArrayObject))
#8 C:\xampp\htdocs\cakephp-3-1-1\vendor\cakephp\cakephp\src\Database\Connection.php(546): Cake\ORM\Table->Cake\ORM\{closure}(Object(Cake\Database\Connection))
#9 C:\xampp\htdocs\cakephp-3-1-1\vendor\cakephp\cakephp\src\ORM\Table.php(1378): Cake\Database\Connection->transactional(Object(Closure))
#10 C:\xampp\htdocs\cakephp-3-1-1\src\Controller\OrderpizzaController.php(58): Cake\ORM\Table->save(Object(Cake\ORM\Entity))
#11 [internal function]: App\Controller\OrderpizzaController->add()
#12 C:\xampp\htdocs\cakephp-3-1-1\vendor\cakephp\cakephp\src\Controller\Controller.php(429): call_user_func_array(Array, Array)
#13 C:\xampp\htdocs\cakephp-3-1-1\vendor\cakephp\cakephp\src\Routing\Dispatcher.php(114): Cake\Controller\Controller->invokeAction()
#14 C:\xampp\htdocs\cakephp-3-1-1\vendor\cakephp\cakephp\src\Routing\Dispatcher.php(87): Cake\Routing\Dispatcher->_invoke(Object(App\Controller\OrderpizzaController))
#15 C:\xampp\htdocs\cakephp-3-1-1\webroot\index.php(37): Cake\Routing\Dispatcher->dispatch(Object(Cake\Network\Request), Object(Cake\Network\Response))
#16 {main}


2015-11-09 04:55:47 Error: [PDOException] SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'toppings' cannot be null
Request URL: /cakephp-3-1-1/orderpizza/add
Stack Trace:
#0 C:\xampp\htdocs\cakephp-3-1-1\vendor\cakephp\cakephp\src\Database\Statement\MysqlStatement.php(36): PDOStatement->execute(NULL)
#1 C:\xampp\htdocs\cakephp-3-1-1\vendor\cakephp\cakephp\src\Database\Statement\StatementDecorator.php(171): Cake\Database\Statement\MysqlStatement->execute(NULL)
#2 C:\xampp\htdocs\cakephp-3-1-1\vendor\cakephp\cakephp\src\Database\Log\LoggingStatement.php(56): Cake\Database\Statement\StatementDecorator->execute(NULL)
#3 C:\xampp\htdocs\cakephp-3-1-1\vendor\cakephp\cakephp\src\Database\Connection.php(270): Cake\Database\Log\LoggingStatement->execute()
#4 C:\xampp\htdocs\cakephp-3-1-1\vendor\cakephp\cakephp\src\Database\Query.php(174): Cake\Database\Connection->run(Object(Cake\ORM\Query))
#5 C:\xampp\htdocs\cakephp-3-1-1\vendor\cakephp\cakephp\src\ORM\Table.php(1530): Cake\Database\Query->execute()
#6 C:\xampp\htdocs\cakephp-3-1-1\vendor\cakephp\cakephp\src\ORM\Table.php(1446): Cake\ORM\Table->_insert(Object(Cake\ORM\Entity), Array)
#7 C:\xampp\htdocs\cakephp-3-1-1\vendor\cakephp\cakephp\src\ORM\Table.php(1377): Cake\ORM\Table->_processSave(Object(Cake\ORM\Entity), Object(ArrayObject))
#8 C:\xampp\htdocs\cakephp-3-1-1\vendor\cakephp\cakephp\src\Database\Connection.php(546): Cake\ORM\Table->Cake\ORM\{closure}(Object(Cake\Database\Connection))
#9 C:\xampp\htdocs\cakephp-3-1-1\vendor\cakephp\cakephp\src\ORM\Table.php(1378): Cake\Database\Connection->transactional(Object(Closure))
#10 C:\xampp\htdocs\cakephp-3-1-1\src\Controller\OrderpizzaController.php(58): Cake\ORM\Table->save(Object(Cake\ORM\Entity))
#11 [internal function]: App\Controller\OrderpizzaController->add()
#12 C:\xampp\htdocs\cakephp-3-1-1\vendor\cakephp\cakephp\src\Controller\Controller.php(429): call_user_func_array(Array, Array)
#13 C:\xampp\htdocs\cakephp-3-1-1\vendor\cakephp\cakephp\src\Routing\Dispatcher.php(114): Cake\Controller\Controller->invokeAction()
#14 C:\xampp\htdocs\cakephp-3-1-1\vendor\cakephp\cakephp\src\Routing\Dispatcher.php(87): Cake\Routing\Dispatcher->_invoke(Object(App\Controller\OrderpizzaController))
#15 C:\xampp\htdocs\cakephp-3-1-1\webroot\index.php(37): Cake\Routing\Dispatcher->dispatch(Object(Cake\Network\Request), Object(Cake\Network\Response))
#16 {main}


2015-11-09 04:55:52 Error: [PDOException] SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'toppings' cannot be null
Request URL: /cakephp-3-1-1/orderpizza/add
Stack Trace:
#0 C:\xampp\htdocs\cakephp-3-1-1\vendor\cakephp\cakephp\src\Database\Statement\MysqlStatement.php(36): PDOStatement->execute(NULL)
#1 C:\xampp\htdocs\cakephp-3-1-1\vendor\cakephp\cakephp\src\Database\Statement\StatementDecorator.php(171): Cake\Database\Statement\MysqlStatement->execute(NULL)
#2 C:\xampp\htdocs\cakephp-3-1-1\vendor\cakephp\cakephp\src\Database\Log\LoggingStatement.php(56): Cake\Database\Statement\StatementDecorator->execute(NULL)
#3 C:\xampp\htdocs\cakephp-3-1-1\vendor\cakephp\cakephp\src\Database\Connection.php(270): Cake\Database\Log\LoggingStatement->execute()
#4 C:\xampp\htdocs\cakephp-3-1-1\vendor\cakephp\cakephp\src\Database\Query.php(174): Cake\Database\Connection->run(Object(Cake\ORM\Query))
#5 C:\xampp\htdocs\cakephp-3-1-1\vendor\cakephp\cakephp\src\ORM\Table.php(1530): Cake\Database\Query->execute()
#6 C:\xampp\htdocs\cakephp-3-1-1\vendor\cakephp\cakephp\src\ORM\Table.php(1446): Cake\ORM\Table->_insert(Object(Cake\ORM\Entity), Array)
#7 C:\xampp\htdocs\cakephp-3-1-1\vendor\cakephp\cakephp\src\ORM\Table.php(1377): Cake\ORM\Table->_processSave(Object(Cake\ORM\Entity), Object(ArrayObject))
#8 C:\xampp\htdocs\cakephp-3-1-1\vendor\cakephp\cakephp\src\Database\Connection.php(546): Cake\ORM\Table->Cake\ORM\{closure}(Object(Cake\Database\Connection))
#9 C:\xampp\htdocs\cakephp-3-1-1\vendor\cakephp\cakephp\src\ORM\Table.php(1378): Cake\Database\Connection->transactional(Object(Closure))
#10 C:\xampp\htdocs\cakephp-3-1-1\src\Controller\OrderpizzaController.php(58): Cake\ORM\Table->save(Object(Cake\ORM\Entity))
#11 [internal function]: App\Controller\OrderpizzaController->add()
#12 C:\xampp\htdocs\cakephp-3-1-1\vendor\cakephp\cakephp\src\Controller\Controller.php(429): call_user_func_array(Array, Array)
#13 C:\xampp\htdocs\cakephp-3-1-1\vendor\cakephp\cakephp\src\Routing\Dispatcher.php(114): Cake\Controller\Controller->invokeAction()
#14 C:\xampp\htdocs\cakephp-3-1-1\vendor\cakephp\cakephp\src\Routing\Dispatcher.php(87): Cake\Routing\Dispatcher->_invoke(Object(App\Controller\OrderpizzaController))
#15 C:\xampp\htdocs\cakephp-3-1-1\webroot\index.php(37): Cake\Routing\Dispatcher->dispatch(Object(Cake\Network\Request), Object(Cake\Network\Response))
#16 {main}


2015-11-09 05:03:08 Warning: Warning (4096): Argument 3 passed to Cake\View\Helper\HtmlHelper::link() must be of the type array, string given, called in C:\xampp\htdocs\cakephp-3-1-1\src\Template\Orderpizza\index.ctp on line 22 and defined in [C:\xampp\htdocs\cakephp-3-1-1\vendor\cakephp\cakephp\src\View\Helper\HtmlHelper.php, line 333]
Trace:
Cake\Error\BaseErrorHandler::handleError() - CORE\src\Error\BaseErrorHandler.php, line 138
Cake\View\Helper\HtmlHelper::link() - CORE\src\View\Helper\HtmlHelper.php, line 333
include - APP/Template\Orderpizza\index.ctp, line 22
Cake\View\View::_evaluate() - CORE\src\View\View.php, line 970
Cake\View\View::_render() - CORE\src\View\View.php, line 930
Cake\View\View::render() - CORE\src\View\View.php, line 578
Cake\Controller\Controller::render() - CORE\src\Controller\Controller.php, line 611
Cake\Routing\Dispatcher::_invoke() - CORE\src\Routing\Dispatcher.php, line 120
Cake\Routing\Dispatcher::dispatch() - CORE\src\Routing\Dispatcher.php, line 87
[main] - ROOT\webroot\index.php, line 37



2015-11-09 05:03:17 Warning: Warning (4096): Argument 3 passed to Cake\View\Helper\HtmlHelper::link() must be of the type array, string given, called in C:\xampp\htdocs\cakephp-3-1-1\src\Template\Orderpizza\index.ctp on line 22 and defined in [C:\xampp\htdocs\cakephp-3-1-1\vendor\cakephp\cakephp\src\View\Helper\HtmlHelper.php, line 333]
Trace:
Cake\Error\BaseErrorHandler::handleError() - CORE\src\Error\BaseErrorHandler.php, line 138
Cake\View\Helper\HtmlHelper::link() - CORE\src\View\Helper\HtmlHelper.php, line 333
include - APP/Template\Orderpizza\index.ctp, line 22
Cake\View\View::_evaluate() - CORE\src\View\View.php, line 970
Cake\View\View::_render() - CORE\src\View\View.php, line 930
Cake\View\View::render() - CORE\src\View\View.php, line 578
Cake\Controller\Controller::render() - CORE\src\Controller\Controller.php, line 611
Cake\Routing\Dispatcher::_invoke() - CORE\src\Routing\Dispatcher.php, line 120
Cake\Routing\Dispatcher::dispatch() - CORE\src\Routing\Dispatcher.php, line 87
[main] - ROOT\webroot\index.php, line 37



2015-11-09 05:03:42 Warning: Warning (4096): Argument 3 passed to Cake\View\Helper\HtmlHelper::link() must be of the type array, string given, called in C:\xampp\htdocs\cakephp-3-1-1\src\Template\Orderpizza\index.ctp on line 22 and defined in [C:\xampp\htdocs\cakephp-3-1-1\vendor\cakephp\cakephp\src\View\Helper\HtmlHelper.php, line 333]
Trace:
Cake\Error\BaseErrorHandler::handleError() - CORE\src\Error\BaseErrorHandler.php, line 138
Cake\View\Helper\HtmlHelper::link() - CORE\src\View\Helper\HtmlHelper.php, line 333
include - APP/Template\Orderpizza\index.ctp, line 22
Cake\View\View::_evaluate() - CORE\src\View\View.php, line 970
Cake\View\View::_render() - CORE\src\View\View.php, line 930
Cake\View\View::render() - CORE\src\View\View.php, line 578
Cake\Controller\Controller::render() - CORE\src\Controller\Controller.php, line 611
Cake\Routing\Dispatcher::_invoke() - CORE\src\Routing\Dispatcher.php, line 120
Cake\Routing\Dispatcher::dispatch() - CORE\src\Routing\Dispatcher.php, line 87
[main] - ROOT\webroot\index.php, line 37



2015-11-09 05:03:46 Warning: Warning (4096): Argument 3 passed to Cake\View\Helper\HtmlHelper::link() must be of the type array, string given, called in C:\xampp\htdocs\cakephp-3-1-1\src\Template\Orderpizza\index.ctp on line 22 and defined in [C:\xampp\htdocs\cakephp-3-1-1\vendor\cakephp\cakephp\src\View\Helper\HtmlHelper.php, line 333]
Trace:
Cake\Error\BaseErrorHandler::handleError() - CORE\src\Error\BaseErrorHandler.php, line 138
Cake\View\Helper\HtmlHelper::link() - CORE\src\View\Helper\HtmlHelper.php, line 333
include - APP/Template\Orderpizza\index.ctp, line 22
Cake\View\View::_evaluate() - CORE\src\View\View.php, line 970
Cake\View\View::_render() - CORE\src\View\View.php, line 930
Cake\View\View::render() - CORE\src\View\View.php, line 578
Cake\Controller\Controller::render() - CORE\src\Controller\Controller.php, line 611
Cake\Routing\Dispatcher::_invoke() - CORE\src\Routing\Dispatcher.php, line 120
Cake\Routing\Dispatcher::dispatch() - CORE\src\Routing\Dispatcher.php, line 87
[main] - ROOT\webroot\index.php, line 37



2015-11-09 05:17:06 Error: [Cake\Datasource\Exception\InvalidPrimaryKeyException] Record not found in table "orderpizza" with primary key [NULL]
Request URL: /cakephp-3-1-1/orderpizza/edit
Stack Trace:
#0 C:\xampp\htdocs\cakephp-3-1-1\src\Controller\OrderpizzaController.php(70): Cake\ORM\Table->get(NULL)
#1 [internal function]: App\Controller\OrderpizzaController->edit()
#2 C:\xampp\htdocs\cakephp-3-1-1\vendor\cakephp\cakephp\src\Controller\Controller.php(429): call_user_func_array(Array, Array)
#3 C:\xampp\htdocs\cakephp-3-1-1\vendor\cakephp\cakephp\src\Routing\Dispatcher.php(114): Cake\Controller\Controller->invokeAction()
#4 C:\xampp\htdocs\cakephp-3-1-1\vendor\cakephp\cakephp\src\Routing\Dispatcher.php(87): Cake\Routing\Dispatcher->_invoke(Object(App\Controller\OrderpizzaController))
#5 C:\xampp\htdocs\cakephp-3-1-1\webroot\index.php(37): Cake\Routing\Dispatcher->dispatch(Object(Cake\Network\Request), Object(Cake\Network\Response))
#6 {main}


2015-11-09 05:18:35 Error: [Cake\Datasource\Exception\InvalidPrimaryKeyException] Record not found in table "orderpizza" with primary key [NULL]
Request URL: /cakephp-3-1-1/orderpizza/edit
Stack Trace:
#0 C:\xampp\htdocs\cakephp-3-1-1\src\Controller\OrderpizzaController.php(70): Cake\ORM\Table->get(NULL)
#1 [internal function]: App\Controller\OrderpizzaController->edit()
#2 C:\xampp\htdocs\cakephp-3-1-1\vendor\cakephp\cakephp\src\Controller\Controller.php(429): call_user_func_array(Array, Array)
#3 C:\xampp\htdocs\cakephp-3-1-1\vendor\cakephp\cakephp\src\Routing\Dispatcher.php(114): Cake\Controller\Controller->invokeAction()
#4 C:\xampp\htdocs\cakephp-3-1-1\vendor\cakephp\cakephp\src\Routing\Dispatcher.php(87): Cake\Routing\Dispatcher->_invoke(Object(App\Controller\OrderpizzaController))
#5 C:\xampp\htdocs\cakephp-3-1-1\webroot\index.php(37): Cake\Routing\Dispatcher->dispatch(Object(Cake\Network\Request), Object(Cake\Network\Response))
#6 {main}


2015-11-09 05:33:52 Error: [Cake\Routing\Exception\MissingControllerException] Controller class Pizza could not be found.
Exception Attributes: array (
  'class' => 'Pizza',
  'plugin' => NULL,
  'prefix' => NULL,
  '_ext' => NULL,
)
Request URL: /cakephp-3-1-1/pizza/
Stack Trace:
#0 C:\xampp\htdocs\cakephp-3-1-1\webroot\index.php(37): Cake\Routing\Dispatcher->dispatch(Object(Cake\Network\Request), Object(Cake\Network\Response))
#1 {main}


2015-11-09 05:34:23 Error: [Cake\Routing\Exception\MissingControllerException] Controller class Pizza could not be found.
Exception Attributes: array (
  'class' => 'Pizza',
  'plugin' => NULL,
  'prefix' => NULL,
  '_ext' => NULL,
)
Request URL: /cakephp-3-1-1/Pizza/add/
Stack Trace:
#0 C:\xampp\htdocs\cakephp-3-1-1\webroot\index.php(37): Cake\Routing\Dispatcher->dispatch(Object(Cake\Network\Request), Object(Cake\Network\Response))
#1 {main}


2015-11-09 05:38:29 Error: [Cake\Controller\Exception\MissingActionException] Action OrderpizzaController::success() could not be found, or is not accessible.
Exception Attributes: array (
  'controller' => 'OrderpizzaController',
  'action' => 'success',
  'prefix' => '',
  'plugin' => NULL,
)
Request URL: /cakephp-3-1-1/orderpizza/success
Stack Trace:
#0 C:\xampp\htdocs\cakephp-3-1-1\vendor\cakephp\cakephp\src\Routing\Dispatcher.php(114): Cake\Controller\Controller->invokeAction()
#1 C:\xampp\htdocs\cakephp-3-1-1\vendor\cakephp\cakephp\src\Routing\Dispatcher.php(87): Cake\Routing\Dispatcher->_invoke(Object(App\Controller\OrderpizzaController))
#2 C:\xampp\htdocs\cakephp-3-1-1\webroot\index.php(37): Cake\Routing\Dispatcher->dispatch(Object(Cake\Network\Request), Object(Cake\Network\Response))
#3 {main}


